apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apiapp1.fullname" . }}
  labels:
    {{- include "apiapp1.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apiapp1.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apiapp1.selectorLabels" . | nindent 8 }}
      annotations: 
        prometheus.io/scrape: "true"
        prometheus.io/path: "{{ index .Values.paths 0 }}/metrics"
        prometheus.io/port: {{ .Values.port | quote }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DB
            valueFrom:
              secretKeyRef:
                key: db
                name: secret-db
          - name: pathBase
            valueFrom:
              secretKeyRef:
                key: pathbase
                name: secret-db
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
