apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apiapp1-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/default-gateway
  http:
  - match:
    - uri:
        prefix: /apiapp1
    route:
    - destination:
        host: apiapp1-a.apiapp1.svc.cluster.local
        port:
          number: 8888